import {EMPTY_UNICODE} from "./constants"
import {Code, Symbol} from "./types"

const GENERIC_COMBINING_STAFF_POSITIONS: Record<Code, Symbol> = {
    /*U+EB97*/[Code["up8"]]: {unicode: "", width: 0},
    /*U+EB96*/[Code["up7"]]: {unicode: "", width: 0},
    /*U+EB95*/[Code["up6"]]: {unicode: "", width: 0},
    /*U+EB94*/[Code["up5"]]: {unicode: "", width: 0},
    /*U+EB93*/[Code["up4"]]: {unicode: "", width: 0},
    /*U+EB92*/[Code["up3"]]: {unicode: "", width: 0},
    /*U+EB91*/[Code["up2"]]: {unicode: "", width: 0},
    /*U+EB90*/[Code["up1"]]: {unicode: "", width: 0},
    /* N/A  */[Code["md0"]]: {unicode: EMPTY_UNICODE, width: 0},
    /*U+EB98*/[Code["dn1"]]: {unicode: "", width: 0},
    /*U+EB99*/[Code["dn2"]]: {unicode: "", width: 0},
    /*U+EB9A*/[Code["dn3"]]: {unicode: "", width: 0},
    /*U+EB9B*/[Code["dn4"]]: {unicode: "", width: 0},
    /*U+EB9C*/[Code["dn5"]]: {unicode: "", width: 0},
    /*U+EB9D*/[Code["dn6"]]: {unicode: "", width: 0},
    /*U+EB9E*/[Code["dn7"]]: {unicode: "", width: 0},
    /*U+EB9F*/[Code["dn8"]]: {unicode: "", width: 0},
} as Record<Code, Symbol>

const TREBLE_COMBINING_STAFF_POSITION_MAP: Record<Code, Symbol> = {
    [Code["c6"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up8"]],
    [Code["b5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up7"]],
    [Code["a5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up6"]],
    [Code["g5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up5"]],
    [Code["f5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up4"]],
    [Code["e5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up3"]],
    [Code["d5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up2"]],
    [Code["c5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up1"]],
    [Code["b4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["md0"]],
    [Code["a4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn1"]],
    [Code["g4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn2"]],
    [Code["f4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn3"]],
    [Code["e4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn4"]],
    [Code["d4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn5"]],
    [Code["c4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn6"]],
    [Code["b3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn7"]],
    [Code["a3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn8"]],
} as Record<Code, Symbol>

const BASS_COMBINING_STAFF_POSITION_MAP: Record<Code, Symbol> = {
    [Code["e4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up8"]],
    [Code["d4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up7"]],
    [Code["c4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up6"]],
    [Code["b3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up5"]],
    [Code["a3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up4"]],
    [Code["g3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up3"]],
    [Code["f3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up2"]],
    [Code["e3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up1"]],
    [Code["d3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["md0"]],
    [Code["c3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn1"]],
    [Code["b2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn2"]],
    [Code["a2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn3"]],
    [Code["g2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn4"]],
    [Code["f2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn5"]],
    [Code["e2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn6"]],
    [Code["d2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn7"]],
    [Code["c2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn8"]],
} as Record<Code, Symbol>

const CLEF_SPECIFIED_COMBINING_STAFF_POSITION_MAP: Record<Code, Symbol> = {
    [Code["trc6"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up8"]],
    [Code["trb5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up7"]],
    [Code["tra5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up6"]],
    [Code["trg5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up5"]],
    [Code["trf5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up4"]],
    [Code["tre5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up3"]],
    [Code["trd5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up2"]],
    [Code["trc5"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up1"]],
    [Code["trb4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["md0"]],
    [Code["tra4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn1"]],
    [Code["trg4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn2"]],
    [Code["trf4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn3"]],
    [Code["tre4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn4"]],
    [Code["trd4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn5"]],
    [Code["trc4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn6"]],
    [Code["trb3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn7"]],
    [Code["tra3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn8"]],
    [Code["bse4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up8"]],
    [Code["bsd4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up7"]],
    [Code["bsc4"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up6"]],
    [Code["bsb3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up5"]],
    [Code["bsa3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up4"]],
    [Code["bsg3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up3"]],
    [Code["bsf3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up2"]],
    [Code["bse3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["up1"]],
    [Code["bsd3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["md0"]],
    [Code["bsc3"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn1"]],
    [Code["bsb2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn2"]],
    [Code["bsa2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn3"]],
    [Code["bsg2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn4"]],
    [Code["bsf2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn5"]],
    [Code["bse2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn6"]],
    [Code["bsd2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn7"]],
    [Code["bsc2"]]: GENERIC_COMBINING_STAFF_POSITIONS[Code["dn8"]],
} as Record<Code, Symbol>

const COMBINING_STAFF_POSITION_MAP: Record<Code, Symbol> = {
    ...BASS_COMBINING_STAFF_POSITION_MAP,
    ...TREBLE_COMBINING_STAFF_POSITION_MAP, // Yes, I realize this is overriding bass. But it's for the unicodes list.
    ...GENERIC_COMBINING_STAFF_POSITIONS,
    ...CLEF_SPECIFIED_COMBINING_STAFF_POSITION_MAP,
}

export {
    BASS_COMBINING_STAFF_POSITION_MAP,
    TREBLE_COMBINING_STAFF_POSITION_MAP,
    CLEF_SPECIFIED_COMBINING_STAFF_POSITION_MAP,
    COMBINING_STAFF_POSITION_MAP,
}
