export {smarts} from "./globals"
export {computeSmartAdvanceAndSmartStavePrefixUnicodeAndUpdateSmarts, updateSmartAdvance} from "./advance"
export {INITIAL_SMARTS} from "./constants"
export {computeSmartPositionUnicode, updateSmartPosition} from "./position"
export {updateSmartClef} from "./clef"
export {updateSmartStave} from "./stave"
export {updateSmarts} from "./update"
export {shouldNotBeDisplayed} from "./shouldNotBeDisplayed"
