export {smarts} from "./globals"
export {computeMaybeAdvancedUnicodeAndMaybeRecordSmartAdvanceAndSmartClef, updateSmartAdvance} from "./advance"
export {INITIAL_SMARTS} from "./constants"
export {computeMaybePositionedUnicode, updateSmartPosition} from "./position"
export {updateSmartClef} from "./clef"
export {updateSmartStave} from "./staves"
export {updateSmarts} from "./update"
